# Generated by Django 5.1.1 on 2024-10-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Pacientes',
        ),
    ]
