# Generated by Django 5.1.1 on 2024-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_hospital_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
    ]
