# Generated by Django 5.1.1 on 2024-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_pacientes_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('crm', models.CharField(max_length=6)),
                ('horarios', models.CharField(max_length=20)),
                ('especialidade', models.CharField(max_length=30)),
            ],
        ),
    ]
