# Generated by Django 5.1.1 on 2024-10-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_medicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='horarios',
        ),
    ]
