# Generated by Django 5.0.7 on 2024-10-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_medicos_crm_alter_pacientes_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='consultas',
            field=models.ManyToManyField(to='hospital.pacientes'),
        ),
    ]
