# Generated by Django 5.0.7 on 2024-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_medicos_consultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('med_esp', models.ManyToManyField(to='hospital.medicos')),
            ],
        ),
    ]
