# Generated by Django 5.0.7 on 2024-10-21 12:00

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=13)),
                ('dono', models.OneToOneField(on_delete=hospital.models.Medicos, to='hospital.pacientes')),
            ],
        ),
    ]
