# Generated by Django 5.0.7 on 2024-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_telefones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='endereco',
            new_name='logradouro',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='estado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
