# Generated by Django 5.1.1 on 2024-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='medicos',
            name='cidade',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medicos',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='medicos',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='medicos',
            name='estado',
            field=models.CharField(default='', max_length=20),
        ),
    ]
