# Generated by Django 5.1.1 on 2024-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_medicos_cep_medicos_cidade_medicos_cpf_medicos_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='logradouro',
            field=models.CharField(default='', max_length=50),
        ),
    ]
