# Generated by Django 5.1.1 on 2024-10-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_medicos_logradouro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='med_esp',
        ),
        migrations.AddField(
            model_name='especialidades',
            name='medico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.medicos'),
        ),
    ]
