# Generated by Django 5.1.1 on 2024-10-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_remove_especialidades_med_esp_especialidades_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicos'),
        ),
    ]
