# Generated by Django 5.1.1 on 2024-10-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_alter_especialidades_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='medico',
        ),
        migrations.AlterField(
            model_name='medicos',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.especialidades'),
        ),
    ]
