# Generated by Django 5.1.1 on 2024-10-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_remove_especialidades_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='especialidades',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.especialidades'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='especialidade',
            field=models.CharField(max_length=30),
        ),
    ]
