# Generated by Django 5.0.4 on 2024-11-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_medicos_especialidades_alter_medicos_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='especialidades',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hospital.especialidades'),
        ),
    ]
